Repository hapijs/hapijs.com, pull requests merged in 2018-03, with the labels that each got.

#546 Update Cookie tutorial for v17
  lib/tutorials/en_US/cookies.md
Labels: documentation

#543 Update Auth Tutorial for v17
  lib/tutorials/en_US/auth.md
Labels: documentation

#548 Update plugins tutorial for hapi 17
  lib/tutorials/en_US/plugins.md
Labels: documentation

#550 Update logging tutorial for hapi 17
  lib/tutorials/en_US/logging.md
Labels: documentation

#553 Update views tutorial for hapi 17
  lib/tutorials/en_US/views.md
Labels: documentation

#556 Update routing tutorial to hapi 17
  lib/tutorials/en_US/routing.md
Labels: documentation

#558 Update server methods tutorial for hapi 17
  lib/tutorials/en_US/server-methods.md
Labels: documentation

#564 Use API tag as part of cache key
  lib/github.js
Labels: bug

#567 Update validation tutorial for hapi 17
  lib/tutorials/en_US/validation.md
Labels: documentation

#518 Tutorials translate into Korean
  lib/tutorials/index.js
  lib/tutorials/ko_KR/auth.md
  lib/tutorials/ko_KR/caching.md
  lib/tutorials/ko_KR/cookies.md
  lib/tutorials/ko_KR/getting-started.md
  lib/tutorials/ko_KR/index.js
  lib/tutorials/ko_KR/logging.md
  lib/tutorials/ko_KR/plugins.md
  lib/tutorials/ko_KR/routing.md
  lib/tutorials/ko_KR/server-methods.md
  lib/tutorials/ko_KR/serving-files.md
  lib/tutorials/ko_KR/validation.md
  lib/tutorials/ko_KR/views.md
Labels: documentation, enhancement

#570 Update caching tutorial for hapi 17
  lib/tutorials/en_US/caching.md
  lib/tutorials/en_US/getting-started.md
  templates/tutorial.pug
Labels: documentation

#572 Fix slack invite link
  lib/tutorials/en_US/getting-started.md
  templates/index.pug
Labels: bug

#574 use tag interpolation for whitespace control
  templates/index.pug
Labels: bug
